DaleStudy/homepage

README.md
- add Web Components
- close #3
=> add Tech Stacks

components/seo-meta-tag/seo-meta-tag.js, index.html, main.js
이번 pr에서는 충돌우려로 component를 위한 js파일만 생성하고 html에 따로 임포트하지 않았습니다! 
html에서 사용하려면` seo-meta-tag.js` 파일 import 해준 뒤 ```<seo-meta-tag title="sample", description="sample description></seo-meta-tag>``` 과 같이 attribute로 접근해서 값을 변경할 수 있습니다. 
SPA로 개발 예정으로 알고 있어서 동적으로 값을 변경할 경우를 고려하여 web component의 lifecycle hook을 이용해서 attribute을 접근합니다.
=> feat : implemented seo-meta-tag component

components/link-button/link-button.css, components/link-button/link-button.js, index.html, main.js
- Close #11 
- 자잘한 스타일은 추후에 수정할 예정입니다.
=> feat: add link button component

.github/CODEOWNERS, .github/pull_request_template.md
As agreed in the last meeting, we're adding a PR template to remind the team of what needs to be checked before merging their code. Please feel free to suggest any additional checklist items you would like to be included. 😄
=> PR Template

index.html
During the meeting, we agreed to format the code in the `index.html` file using the default Prettier config. This will help the team to format the code consistently going forward. If you've customized the Prettier config and it can format the code differently, please disable the `format on save` feature in VSCode before editing the `index.html` file.
=> Format index.html with default Pretter config

CONTRIBUTING.md, README.md
=> feat: add CONTRIBUTING.md

CONTRIBUTING.md, README.md
=> docs: update contributing and readme docs

components/hero.js, index.html, main.js
=> feat : Make Hero component responsive

components/footer-icon.js
Footer-Icon에서 발생한 에러 다시 수정해서 올립니다. 기존 코드가 최대 길이를 잡아서 확장자 체크를 했었는데, 이 부분에서 에러가 발생한 것 같네요. . 을 기준으로 확장자 마지막 부분을 변경하도록 재수정했습니다.
=> Fix footer-icon validateAttributes

global-styles.css
=> feat: Add font weight variables for Spoqa Han Sans Neo

components/image.js, components/intro-section.js, global-styles.css, index.html
=> refactor: intro section component

index.html
=> fix: remove unnecessary inline style code in step component

components/code-review-section.js, index.html, main.js
=> feat : create code-review-section component

components/header.js
=> fix : modify margin for mobile view to have 27px on the side

components/participant-review-section.js
=> fix: remove percent and add margin to modify layout for mobile view of ParticipantReviewSectioin

components/step-section.js
=> fix: remove percent and add margin to modify layout for mobile view of StepSection

components/participant-review.js, components/step.js, index.html
=> fix: attribute name from camelCase to kebab-case

index.html
=> fix: remove async, defer attributes in script tag

index.html
=> fix: <html> element does not have a [lang] attribute

components/footer-link-list.js, index.html
=> fix: ul, li problems for a11y

components/code-review-section.js, components/step-section.js
=> fix: background color

components/header.js
=> fix : add weight for hover for a span and change the a tags padding

components/step.js, global-styles.css
=> feat : add hover style to 200ms for all button and a element

components/header.js
=> fix : remove box shadow style from tablet

components/header.js
=> fix : change a link to the current  home page url

index.html
=> 2기 모집을 위한 스터디 신청 링크 변경

components/participant-review.js
=> fix: link issue in author of ParticipantReviewItem

components/steps-section.js
스터디 참여 방법 1 단계를 현재 진행 중인 스터디 기수에 맞게 업데이트합니다.
=> 스터디 참여 방법 1 단계 업데이트

data.js
=> 프로젝트 보드 URL 업데이트

components/language-section.js
=> refactor: simplify styling for language section

index.html
웹사이트 트래픽 수집을 위해서 Google Analytics 설치합니다.
=> Google Analytics 설치

components/header.js, data.js
=> 헤더 내에 리더보드 버튼 추가 및 워딩 변경 

.github/CODEOWNERS, .github/FUNDING.yml, .github/workflows/automation.yml, CONTRIBUTING.md, LICENSE, README.md
홈페이지 프로젝트에 라이선스를 추가하고 깃허브 후원 버튼을 답니다.
=> 라이선스 + 스폰서

components/header.js
=> feat: 후원하기 버튼
