DaleStudy/homepage

- .github/CODEOWNERS
- .github/workflows/automation.yml
자동으로 PR에 코드 작성자가 할당되도록 GitHub Actions 워크플로우를 추가합니다.
> CODEOWNERS + PR Auto-assignment

- components/footer-link/footer-link.js
웹사이트를 둘러보다가 우연히 콘솔에서 다음 오류를 발견하였습니다. 간단한 버그라서 바로 고칩니다.
- close #31 
- close #29
> fix: merge two constructors in footerlink

- components/header.js
- Extra changes
- delete import statement in the header.js because it doesn't have to be imported in the header.js
> fix: solve passing wrong attributes bug

- html-css-utils.js
> feat: add util functions for html and css

- components/button-link.js
- components/header.js
- global-styles.css
- index.html
> feat: update button-link with new pattern

- components/image.js
- index.html
- main.js
> feat : create image component

- components/header.js
- index.html
> Fix : Update deprecated class join-instruction-container to steps section to make it functional

- components/step.js
각 스크린 사이즈에 따른, '스터디 참여방법' 타이틀과 'step-list'간의 간격을 기존 사이즈에만 적용해두고, 태블릿, 데스크톱일 때는 적용해두지 않아서 추가합니다.
> fix: Add missing simple style code to comply with figma

- components/button-link.js
- components/header.js
> style: add button-link border & a11y styles

- components/participant-review-section.js
- components/step-section.js
768px 이후로는 해당 layout(participant-reveiw-section, step-section)들이 다시 80%가 되어야하는데, 링크된 pr들에서 모바일에서는 양쪽 마진을 추가하는 layout으로 수정하며 지금 pr작업을 별도로 해주지 않아서 추가 pr을 올립니다.
> fix: layout with responsive design up to 768px of participant review section and step section

- components/step.js
> style: add accessibility design by state in steps

- components/button-link.js
- components/footer.js
- global-styles.css
> fix: change button-link bg color for high contrast

- components/header.js
> fix : add name to button

- components/footer-link-list.js
- components/header.js
- components/icon-link-list.js
> fix: add aria-label to fix to links to provide discernible names

- components/footer.js
- components/header.js
- index.html
띄어쓰기 대신에 camelCase를 사용하는 영문 브랜딩 관례를 따르기 위한 변경입니다.
> 영어 사이트 이름 정정

- index.html
이슈 리스트 중, 잘못된 디스코드 링크가 삽입되어있는 버그는 빠르게 수정되면 좋을 것 같아 반영합니다.
> fix: wrong discord link in intro and code review section

- components/participant-review.js
- index.html
> feat: add author-link attribute in ParticipantReview

- components/index.js
- index.html
- main.js
- Added display:none to body to hide text until the component is fully loaded
> fix: resolve FOUC issue on initial render of custom elements

- components/image.js
- components/step.js
이슈가 발생하는 이미지 태그에 ```object-fit: contain;``` 속성을 추가하여 해결
> Fixed incorrect aspect ratio issue with object-fit

- components/footer-link-list.js
- components/step-section.js
- data.js
- index.html
PR #186 에서 제가 스터디 2기 모집을 위해서 Steps 섹션에 있는 스터디 신청 URL을 수정했었는데요. 알고보니 Footer에도 스터디 신청 링크가 있었는데 제가 실수록 수정을 빼먹었더라고요. 2기 신청자 분께서 알려주셔서 뒤늦게 발견하게 되었습니다.
예전에 디스코드 URL도 그렇고 저는 비슷한 문제가 계속 반복되고 있는 이유가 HTML 마크업 안에 데이터를 하드코딩해놔서 그런 것 같습니다. 근본적인 해결책은 이렇게 여러 곳에 위치하는데 주기적으로 갱신이 되야하는 데이터는 한 곳에서 관리하는 것(Single Source of Truth)이라고 생각합니다.
우리 프로젝트는 백앤드나 데이터베이스가 없기 때문에 `data.js` 파일에 스터디 신청 URL을 저장해놓고 import를 하려고 했는데요. 뜻밖에 걸림돌에 부딪히게 되었습니다. 다음 두 개의 컴포넌트의 API 설계가 일관적이지 않기 때문입니다.
- `<ds-steps-section>` 요소는 slot을 통해서 외부에서 내용을 넘기도록 되어 있습니다.
- `<footer-link-list>` 요소는 slot을 받지 않고 내부적으로 내용을 랜더링하도록 되어 있습니다.
`<footer-link-list>` 요소의 내용은 자바스크립트 파일(footer-link-list.js)에 있기 때문에, 스터디 신청 URL을 import하는데 아무 문제가 없었습니다. 하지만 `<ds-steps-section>` 요소는 내용은 index.html 파일에 있기 때문에, 스터디 신청 URL을 어떻게 주입해야 할지 고민이 되었습니다.
그래서 임시 방편으로 …
> Footer 안 스터디 신청 URL 정정

- CONTRIBUTING.md
- components/participant-review-section.js
- data.js
디스코드 초대 링크에 대한 단축 URL을 만들었습니다: https://dales.link/discord 
디스코드 초대 링크는 새로 생성할 때 URL내 해시값이 바뀌는데요. 그래서 일일이 찾아서 업데이트해주는 게 번거롭고 놓치기도 쉽습니다. 단축 URL을 사용하면 이러한 문제를 쉽게 예방할 수 있습니다. 단순히 단축 URL이 가리키는 디스코드 초대 링크만 바꿔주면 되니까요.
> 디스코드 링크에 단축 URL 사용

- components/footer-link-list.js
- components/steps-section.js
- data.js
곧 시작하는 스터디 3기를 위해서 웹사이트의 컨텐츠를 업데이트하였습니다.
> 스터디 3기를 위한 웹사이트 컨텐츠 업데이트

- components/steps-section.js
- data.js
> update : link and text
